title: Marie Vrablic # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Enthusiast 
  Educator at heart. Cat mom. Yogini.
  <a href="https://www.linkedin.com/in/marievrablic-dat-a-girl/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
